### ISSUE TITLE
eslint-plugin doesn't support {{yield}}

### ISSUE THREAD

**Issue by wondersloth** [tomdale/glimmer-lite-donut#39]
In my component:
```
export default class Form extends Component {
  static template = hbs`<form ...attributes>
  {{yield}}
</form>`;
}
```

I get an error:
```
Token yield is used in an hbs tagged template literal, but is not definedeslint(@glimmerx/template-vars)
```

I have fixed it using the rules in my `.eslintrc.js` with the following as a work around:
`'@glimmerx/template-vars': ['error', 'all', { nativeTokens: ['yield'] }],`

`{{yield}}` needs to be added to the default set of helpers.

**Comment by chiragpat** [comment]
It also needs support for `has-block` and `unless`, as well as support for named blocks.
